# Generated by Django 5.2.6 on 2025-10-31 08:38

import api.additional_models.carpark_models
import django.contrib.auth.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_id', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('service_no', models.CharField(max_length=10, unique=True)),
                ('operator', models.CharField(max_length=10)),
                ('direction', models.IntegerField(default=1)),
                ('category', models.CharField(default='TRUNK', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='BusStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_stop_code', models.CharField(max_length=50, unique=True)),
                ('road_name', models.CharField(blank=True, max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Carpark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(db_index=True, max_length=100)),
                ('name', models.CharField(db_index=True, max_length=512)),
                ('x_coord', models.FloatField()),
                ('y_coord', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='CarparkSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('availability_api_url', models.URLField()),
                ('info_api_url', models.URLField()),
                ('headers', models.JSONField(blank=True, help_text='allows user to add additional info like api keys', null=True)),
                ('info_path_mapping', models.JSONField(blank=True, default=api.additional_models.carpark_models.default_info_mapping)),
                ('availability_path_mapping', models.JSONField(blank=True, default=api.additional_models.carpark_models.default_availability_mapping)),
            ],
        ),
        migrations.CreateModel(
            name='MRTLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_code', models.CharField(choices=[('NSL', 'North South Line'), ('EWL', 'East West Line'), ('NEL', 'North East Line'), ('CCL', 'Circle Line'), ('DTL', 'Downtown Line'), ('TEL', 'Thomson East Coast Line')], max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TransportAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('PEAK', 'Peak Hour'), ('DISRUPTION', 'Service Disruption'), ('INFO', 'Information')], max_length=20)),
                ('message', models.TextField()),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='MEDIUM', max_length=10)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='CarparkAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available_lots', models.PositiveIntegerField()),
                ('total_lots', models.PositiveIntegerField()),
                ('carpark', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability', to='api.carpark')),
            ],
        ),
        migrations.AddField(
            model_name='carpark',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carparks', to='api.carparksource'),
        ),
        migrations.CreateModel(
            name='FavouriteRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_type', models.CharField(choices=[('bus', 'Bus'), ('mrt', 'MRT')], max_length=10)),
                ('route_id', models.CharField(max_length=50)),
                ('nickname', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourites', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MRTStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('lines', models.ManyToManyField(related_name='stations', to='api.mrtline')),
            ],
        ),
        migrations.CreateModel(
            name='MRTSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrival_time', models.TimeField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.mrtline')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.mrtstation')),
            ],
        ),
        migrations.AddField(
            model_name='mrtline',
            name='end_station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='line_end', to='api.mrtstation'),
        ),
        migrations.AddField(
            model_name='mrtline',
            name='start_station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='line_start', to='api.mrtstation'),
        ),
        migrations.CreateModel(
            name='RealTimeBus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.busroute')),
            ],
        ),
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_transport', models.CharField(choices=[('BUS', 'Bus'), ('MRT', 'MRT'), ('MIXED', 'Mixed')], default='MIXED', max_length=10)),
                ('avoid_crowded_routes', models.BooleanField(default=False)),
                ('receive_alerts', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preference', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BusSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrival_time', models.TimeField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.busroute')),
                ('stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.busstop')),
            ],
            options={
                'unique_together': {('route', 'stop', 'arrival_time')},
            },
        ),
        migrations.AddIndex(
            model_name='carpark',
            index=models.Index(fields=['x_coord', 'y_coord'], name='api_carpark_x_coord_089230_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='carpark',
            unique_together={('source', 'external_id')},
        ),
        migrations.AlterUniqueTogether(
            name='favouriteroute',
            unique_together={('user', 'route_id', 'route_type')},
        ),
        migrations.AlterUniqueTogether(
            name='mrtschedule',
            unique_together={('line', 'station', 'arrival_time')},
        ),
    ]
