# Generated by Django 5.2.6 on 2025-10-30 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='busroute',
            name='route_id',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
