# Generated by Django 5.2.6 on 2025-10-26 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carparkavailability',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='carparkavailability',
            name='available_lots',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='carparkavailability',
            name='carpark',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability', to='api.carpark'),
        ),
        migrations.AlterField(
            model_name='carparkavailability',
            name='total_lots',
            field=models.PositiveIntegerField(),
        ),
    ]
