# Generated by Django 5.2.6 on 2025-10-06 04:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarparkSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('api_url', models.URLField()),
                ('field_mapping', models.JSONField(blank=True, help_text='Maps external fields to internal ones', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Carpark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(db_index=True, max_length=100)),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('available_lots', models.PositiveIntegerField()),
                ('total_lots', models.PositiveIntegerField()),
                ('source_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carparks', to='api.carparksource')),
            ],
            options={
                'indexes': [models.Index(fields=['lat', 'lon'], name='api_carpark_lat_4c78e8_idx')],
                'unique_together': {('source_id', 'external_id')},
            },
        ),
    ]
