# Generated by Django 5.2.6 on 2025-10-22 07:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_carparksource_carpark'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarparkAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available_lots', models.PositiveIntegerField()),
                ('total_lots', models.PositiveIntegerField()),
            ],
        ),
        migrations.RemoveIndex(
            model_name='carpark',
            name='api_carpark_lat_4c78e8_idx',
        ),
        migrations.RenameField(
            model_name='carpark',
            old_name='source_id',
            new_name='source',
        ),
        migrations.RenameField(
            model_name='carpark',
            old_name='lat',
            new_name='x_coord',
        ),
        migrations.RenameField(
            model_name='carpark',
            old_name='lon',
            new_name='y_coord',
        ),
        migrations.RemoveField(
            model_name='carpark',
            name='available_lots',
        ),
        migrations.RemoveField(
            model_name='carpark',
            name='total_lots',
        ),
        migrations.AddField(
            model_name='carparksource',
            name='info_url',
            field=models.URLField(default={}),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='carpark',
            index=models.Index(fields=['x_coord', 'y_coord'], name='api_carpark_x_coord_089230_idx'),
        ),
        migrations.AddField(
            model_name='carparkavailability',
            name='carpark_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability', to='api.carpark'),
        ),
    ]
