# Generated by Django 5.2.6 on 2025-10-22 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_carparkavailability_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carparksource',
            name='headers',
            field=models.JSONField(blank=True, help_text='allows user to add additional info like api keys', null=True),
        ),
    ]
