# Generated by Django 5.2.6 on 2025-10-17 13:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_busstop_busroute_realtimebus_busschedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='MRTStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='MRTLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('end_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_end', to='api.mrtstation')),
                ('start_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_start', to='api.mrtstation')),
            ],
        ),
        migrations.CreateModel(
            name='TransportAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('PEAK', 'Peak Hour'), ('DISRUPTION', 'Service Disruption'), ('INFO', 'Information')], max_length=20)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('affected_mrt_lines', models.ManyToManyField(blank=True, to='api.mrtline')),
                ('affected_routes', models.ManyToManyField(blank=True, to='api.busroute')),
            ],
        ),
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_mode', models.CharField(choices=[('bus', 'Bus'), ('mrt', 'MRT'), ('both', 'Both')], default='both', max_length=20)),
                ('avoid_crowded_routes', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FavouriteRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_type', models.CharField(choices=[('bus', 'Bus'), ('mrt', 'MRT')], max_length=10)),
                ('route_id', models.CharField(max_length=50)),
                ('nickname', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'route_id', 'route_type')},
            },
        ),
        migrations.CreateModel(
            name='MRTSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrival_time', models.TimeField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.mrtline')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.mrtstation')),
            ],
            options={
                'unique_together': {('line', 'station', 'arrival_time')},
            },
        ),
    ]
