# Generated by Django 5.2.6 on 2025-10-17 14:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_mrtstation_mrtline_transportalert_userpreference_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpreference',
            name='preferred_mode',
        ),
        migrations.AddField(
            model_name='userpreference',
            name='preferred_transport',
            field=models.CharField(choices=[('BUS', 'Bus'), ('MRT', 'MRT'), ('MIXED', 'Mixed')], default='MIXED', max_length=10),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='receive_alerts',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preference', to=settings.AUTH_USER_MODEL),
        ),
    ]
