# Generated by Django 5.2.6 on 2025-10-22 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_carparksource_headers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carparksource',
            old_name='api_url',
            new_name='availability_api_url',
        ),
        migrations.RenameField(
            model_name='carparksource',
            old_name='info_url',
            new_name='info_api_url',
        ),
    ]
