# Generated by Django 5.2.6 on 2025-10-24 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_api_url_carparksource_availability_api_url_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carparkavailability',
            old_name='carpark_id',
            new_name='carpark',
        ),
    ]
