# Generated by Django 5.2.6 on 2025-10-26 08:43

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_carpark_id_carparkavailability_carpark'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carparksource',
            name='field_mapping',
        ),
        migrations.AddField(
            model_name='carpark',
            name='name',
            field=models.CharField(db_index=True, default='nothingyet', max_length=512),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carparksource',
            name='availability_path_mapping',
            field=models.JSONField(blank=True, default=api.models.default_availability_mapping),
        ),
        migrations.AddField(
            model_name='carparksource',
            name='info_path_mapping',
            field=models.JSONField(blank=True, default=api.models.default_info_mapping),
        ),
    ]
